### ISSUE TITLE
Worker import method depreciated

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot-plugin-chatops-ansible#31]
### Proposed Functionality

Change `from nautobot_chatops.workers.base import subcommand_of, handle_subcommands`
to `from nautobot_chatops.workers import subcommand_of, handle_subcommands`.

### Use Case

The nautobot_chatops.workers.base is listed as obsolete and will be deprecated.

**Comment by jvanderaa** [comment]
@smk4664 are you good with closing this?

**Comment by jvanderaa** [comment]
Closing with the migration to new chatops.
